### ISSUE TITLE
Remove yarn dependency?

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/symfony-module-tests#2]
Would it be possible to remove the `yarn` dependency? Couldn't all assets be included in the git repo right away?

**Comment by TavoNiievez** [comment]
yes, it is totally possible, and it is something that should be done since the goal of this project is to have the least amount of code possible to execute the tests, and having to compile assets before executing them is definitely not necessary.

However making that change requires editing the 3 branches of this project for each version of Symfony and also the CI workflow in the Symfony module.

PR are welcome.
