### ISSUE TITLE
Suggestion: Rename this to `module-symfony-tests`

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/symfony-module-tests#3]
...to follow the naming convention of the modules at https://github.com/Codeception

**Comment by TavoNiievez** [comment]
Which convention are you referring to exactly?

In the case of Laravel, the (most recent) test project is called `"Codeception/codeception-laravel5-sample"`, in the case of the yii module it is called `"Codeception/yii2-tests"` and in the case of Phalcon `"Codeception/phalcon-demo"`, the previous Symfony project was called `"Codeception/symfony-demo"`, but that was because it is actually a fork of Symfony Demo.

If you have an idea on how to consistently name all those projects, the first step would be to create an ~Issue~ [Discussion](https://github.com/Codeception/Codeception/discussions) in the core project, and depending on what is commented there, make the changes... Which would imply not only renaming them in GitHub but also correcting the CI workflow of all of them so that they work with the new names.

In any case, I agree that they be renamed... *If* and *only if* they **all** follow a real convention.

**Comment by ThomasLandauer** [comment]
Sorry, I thought this is the very first test project!
See https://github.com/Codeception/Codeception/discussions/6052

**Comment by TavoNiievez** [comment]
don't worry, i think it would be a very good proposal, thanks :)

**Comment by TavoNiievez** [comment]
Because this issue really involves all test/demo projects, I am closing this in favor of the created discussion.
