### ISSUE TITLE
Suggestion: Remove unneeded test suites

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/symfony-module-tests#4]
... from https://github.com/Codeception/symfony-module-tests/tree/main/tests

**Comment by TavoNiievez** [comment]
I agree that it is a bit strange that there are empty Test Suites, but they are there in case someone needs to reproduce a bug or wants to test Codeception with a symfony project out of the box.

I'm not sure how or where to explain why they are there.

But maybe a better solution is to add some acceptance or unit tests... Regarding the API Suit... well, maybe that Suite should be removed, but i can't remove `module-rest` as a dependency since the email tests ***(still)*** need a method ***(`stopFollowingRedirect`)*** from that module.

**Comment by ThomasLandauer** [comment]
I would delete them, for the following reasons:
* This is meant to be a *minimal* project
* Creating a suite is easy (CLI command)
* You also cannot include every Symfony component, just because anybody might need it

**Comment by TavoNiievez** [comment]
> Creating a suite is easy (CLI command)

Well, you (sort of) convinced me in this case :)

But to remove them, i have to make sure that it really is easy for someone to create them, especially if they are a total newbie to Codeception. Can you send a PR modifying the `readme.md` to include links to the documentation where it is explained to me how to create the suites if for some reason i need to create them? If so, I gladly remove the unused suites.

> You also cannot include every Symfony component, just because anybody might need it

Not in this case.

If `module-symfony` becomes useful with all (or most) Symfony components, this project should include them (with the minimum configuration possible) to verify that they work with the module.
